# Generated by Django 2.2 on 2019-05-01 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dayoff',
            name='type',
            field=models.CharField(choices=[('0', 'ลากิจ'), ('1', 'ลาป่วย')], default='3', max_length=1),
        ),
    ]
